# Commands go through bash
shell = "bash -c '{}'"

# Neovim
[[items]]
file = "~/.config/nvim/lua/base16-colorscheme.lua"
template = "luatable"
start = "-- Start flavours"
end = "-- End flavours"

# Alacritty
[[items]]
file = "~/.config/alacritty/colorscheme.yml"
template = "alacritty"
rewrite = true

# Polybar
[[items]]
file = "~/.config/polybar/config"
template = "polybar"

# Dunst
[[items]]
file = "~/.config/dunst/dunstrc"
template = "dunst"
